config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :show] do
    resources :user_comments, only: [:new, :create, :destroy]
    resources :goals, only: [:new, :create, :show, :index, :destroy] do
      resources :goal_comments, only: [:new, :create, :destroy]
    end
  end


  resource :session, only: [:new, :create, :destroy]
end

app/models/goal.rb
# == Schema Information
#
# Table name: goals
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  body       :text             not null
#  user_id    :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Goal < ActiveRecord::Base

  validates :title, :body, :user, presence: true

  belongs_to :user
  has_many :goal_comments

end

app/models/goal_comment.rb
class GoalComment < ActiveRecord::Base

  validates :body, :poster, :goal, presence: true

  belongs_to :poster,
    class_name: :User,
    primary_key: :id,
    foreign_key: :poster_id

  belongs_to :goal

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base

  validates :username, :password_digest, :session_token, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }

  has_many :goals

  has_many :goal_comments,
    class_name: :GoalComment,
    primary_key: :id,
    foreign_key: :poster_id

  has_many :posted_user_comments,
    class_name: :UserComment,
    primary_key: :id,
    foreign_key: :poster_id

  has_many :postee_user_comments,
    class_name: :UserComment,
    primary_key: :id,
    foreign_key: :postee_id
  # has_many :comments, as: :commentable

  after_initialize :ensure_session_token

  attr_reader :password

  def self.find_by_credentials(username, password)
    @user = User.find_by_username(username)
    return @user if @user && @user.is_password?(password)
    nil
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64(16)
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save!
    self.session_token
  end
end

app/models/user_comment.rb
class UserComment < ActiveRecord::Base

  validates :body, :poster, :postee, presence: true

  belongs_to :poster,
    class_name: :User,
    primary_key: :id,
    foreign_key: :poster_id

  belongs_to :postee,
    class_name: :User,
    primary_key: :id,
    foreign_key: :postee_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def login(user)
    session[:session_token] = user.reset_session_token!
  end

  def current_user
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def logged_in?
    !!current_user
  end

  def logout
    current_user.reset_session_token!
    session[:session_token] = nil
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController

  def new
    @goal = Goal.new
    render :new
  end

  def create
    @goal = Goal.new(goal_params)
    @goal.user_id = current_user.id

    if @goal.save
      redirect_to user_goals_url(@goal.user)
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :new
    end
  end

  def index
    @goals = current_user.goals
    render :index
  end

  def show
    @goal = Goal.find(params[:id])
    render :show
  end

  def destroy
    @goal = Goal.find(params[:id])
    @goal.destroy
    redirect_to user_goals_url(@goal.user)
  end

  private
  def goal_params
    params.require(:goal).permit(:title, :body)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    render :new
  end

  def create
    @user = User.find_by_credentials(params[:user][:username],
                                     params[:user][:password])

    if @user
      login(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = ["Invalid Credentials"]
      render :new
    end
  end

  def destroy
    logout
    redirect_to new_session_url
  end

end

app/controllers/user_comments_controller.rb
class UserCommentsController < ApplicationController

  def new
    @user_comment = UserComment.new
    render :new
  end

  def create
    @user_comment = UserComment.new(comment_params)
    @user_comment.poster_id = current_user.id
    @user_comment.postee_id = params[:user_id]

    if @user_comment.save
      redirect_to "/users/#{params[:user_id]}"
    else
      flash.now[:errors] = @user_comment.errors.full_messages
      render :new
    end
  end

  private
  def comment_params
    params.require(:user_comment).permit(:body)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    render :show
  end

  private
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_comments_helper.rb
module UserCommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/goals/index.html.erb
<h1><%= current_user.username %>'s Goals</h1>

<%= link_to "Set New Goal", new_user_goal_url %>
<br><br>
<% @goals.each do |goal| %>
  <h2><%= goal.title %></h2>
  <p><%= goal.body %></p>
  <%= button_to  "Remove Goal", "/users/#{current_user.id}/goals/#{goal.id}", method: :delete%>
<% end %>

app/views/goals/new.html.erb
<h1>New Goal</h1>

<form action="<%= user_goals_url  %>" method="post">
  <input type="hidden" name="goal[user_id]" value="<%= current_user.id %>">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token  %>">

  <label>
    Title
    <input type="text" name="goal[title]">
  </label>

  <br>

  <label>
    Body
    <textarea name="goal[body]" rows="8" cols="80"></textarea>
  </label>

  <br>

  <input type="submit" value="Set New Goal">

</form>

app/views/goals/show.html.erb
<h1><%= @goal.title %></h1>

<%= @goal.body %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GoalApp</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>


<% if logged_in? %>
  <%= current_user.username %>
  <%= button_to "Log Out", session_url, method: :delete %>
<% else %>
  <%= link_to "Log In", new_session_url %>
  <%= link_to "Register", new_user_url %>
<% end %>

<%= yield %>

</body>
</html>

app/views/user_comments/new.html.erb
<h1> Comment on <%= User.find_by(id: params[:user_id]).username %>'s Wall</h1>

<form action="<%= user_user_comments_url  %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token  %>">
  <input type="hidden" name="user_comment[poster_id]" value="<%= current_user.id %>">
  <input type="hidden" name="user_comment[postee_id]" value="<%= params[:user_id] %>">



  <label>
    Comment
    <br>
    <textarea name="user_comment[body]" rows="8" cols="80"></textarea>
  </label>

  <br>

  <input type="submit" value="Post Comment">

</form>

app/views/users/new.html.erb
<h1>Register</h1>

<form action="<%= users_url  %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token  %>">

  <label>
    Username
    <input type="text" name="user[username]">
  </label>

  <label>
    Password
    <input type="password" name="user[password]">
  </label>

  <input type="submit" value="Sign Up">

</form>

app/views/users/show.html.erb
<h1><%= @user.username %>'s Profile</h1>

<h2>Wall</h2>
<form action="<%= user_user_comments_url(@user) %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="user_comment[poster_id]" value="<%= current_user.id %>">
  <input type="hidden" name="user_comment[postee_id]" value="<%= params[:user_id] %>">
  <textarea name="user_comment[body]" rows="8" cols="80"></textarea>
  <input type="submit" value="Post On Wall">
</form>
<% @user.postee_user_comments.each do |comment| %>
  <%= comment.poster.username %>:<%= comment.body %>
<% end %>